title: Melissa Smith
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Melissa Smith
permalink: ':title'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Melissa Smith # add your name
author-img: melissa-smith.png # add your photo
about-author: Melissa Smith has been working remotely since 2013. In 2017, she became location independent. During that time she traveled to 16 countries in 12 months while running her business.<br><br>Now Melissa teaches and consults others on how to work remotely and is an author for the first global, online education remote individual certification program with Remote-how Academy. # add description
social-twitter: thepva # add your Twitter handle
social-linkedin: melissasmiththepva # add your Linkedin handle
social-email: 	melissa@thepva.com # add your Email address

# Disqus
discus-identifier: melissasmith # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
